### ISSUE TITLE
glTF import for glTF export

### ISSUE THREAD

**Issue by electroheadfx** [ksons/gltf-blender-importer#15]
It would like awesome to follow the nodes from glTF-Blender-Exporter here:
https://github.com/KhronosGroup/glTF-Blender-Exporter

The workflow: you export a model from substance painter in glTF, you import with your ksons/gltf-blender-importer, you animate the scene in blenber, and export with glTF-Blender-Exporter for ThreeJS, Unity or BabylonJS. Not need to replace the nodes.

**Comment by ksons** [comment]
Good idea @electroheadfx. What does prevent you from doing so?

**Comment by electroheadfx** [comment]
it avoid to remove your node for setup with the glTF-Blender-Exporter's node from kronos-group. The workflow is for webGL

**Comment by aguaviva** [comment]
I think he means he'd like your importer to use the glTF-Blender-Exporter material node
. for example I just imported a huge GLTF but now to export it I would need to replace every single material node (lots of them) with the node glTF-Blender-Exporter needs.

**Comment by scurest** [comment]
So some history on this issue. In the past year

* we switched to using glTF-Blender-Exporter's node groups
* glTF-Blender-Exporter merged with julienduroure's importer to become glTF-Blender-IO, which has the explicit goal of round-tripping successfully
* glTF-Blender-IO abandoned the node-group approach to materials in favor of using Principled BSDF nodes
* we now also use Principled BSDF nodes

In simple cases (eg. Damaged Helmet) we are, as of this moment in v0.5.0, compatible with glTF-Blender-IO. In more complex cases (certainly involving texture transforms or wrapping modes, possibly alpha), we're not. Nothing we currently do could be compatible for wrapping modes since they aren't supported by glTF-Blender-IO atm for example. But our compatibility is quite good, much better than when this issue was opened and if you need compatibility you're probably just going to use the importer in glTF-Blender-IO anyway.
