### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by fire** [ksons/gltf-blender-importer#4]
Can you write some instructions on how to use this?

**Comment by andrehunter** [comment]
How do I install addon?

**Comment by scurest** [comment]
This is for Blender 2.78, but it should work with earlier versions too. This is basically how you install any Blender addon.

1. First, download a copy of this repo. You can do it by downloading and unzipping the [ZIP](https://github.com/ksons/gltf-blender-importer/archive/master.zip).

2. Second, find out where your Blender addon folder is. The most common places for the common OSes are:

    * **Windows**, `C:\Users\<YOUR USER NAME>\AppData\Roaming\Blender Foundation\Blender\<YOUR BLENDER VERSION>\scripts\addons\`
    * **Linux**, `/home/<YOUR USER NAME>/.config/blender/<YOUR BLENDER VERSION>/scripts/addons/`
    * **macOS**, `/Users/<YOUR USER NAME>/Library/Application Support/Blender/<YOUR BLENDER VERSION>/scripts/addons/`

    Alternatively, open Blender, switch to the Python console and enter
    ```
    print(bpy.utils.user_resource('SCRIPTS','addons'))
    ```
    and it should print the addon folder's location.

3. Copy the `io_scene_gltf` folder from this repo that you got in step 1 into the addon folder you found in step 2. The addon is now "installed". You can now delete your copy of the repo from step 1 if you like.

4. Open Blender. select **File > User Preferences** and switch to the **Add-ons** tab. In the search bar, type "gltf". An addon called "Import-Export: glTF 2.0 Importer" should appear (if it doesn't make sure you did the previous steps correctly). Check the tickbox next to the name. The addon is now "enabled".

    Click **Save User Settings** so Blender will remember that you've enabled it next time it loads.

5. You're done! You can import glTF files through the **File > Import > glTF JSON** option.

To update, you'll need to repeat steps 1 and 3.

-----

If you want to develop for the addon (or you want an easier time updating), I recommend replacing step 1 with cloning the repo

    $ git clone https://github.com/ksons/gltf-blender-importer.git

and replacing step 3 with symbolically linking the `io_scene_gltf` folder into the addon folder instead of copying it. On Linux, you can do this with 

    $ cd <YOUR ADDON FOLDER FROM STEP 2>
    $ ln -s <PATH TO THE io_scene_gltf FOLDER>

(I don't know how to do it on Windows/macOS). This means Blender will always use the content of the repo for the addon when it loads so you can eg. switch branches and restart Blender and immediately be using the new branch.

**Comment by iwanPlays** [comment]
thanks for the instructions.

To allow easy 'from zip' installation, please move the script file to the root of the project, so users simply can download and directly use https://github.com/ksons/gltf-blender-importer/archive/master.zip in blender without having to manually invade hidden folders.

**Comment by ksons** [comment]
Picked up your idea of the 'from zip' installation. For each release, we will have a ZIP file linked from the README page as well as from the [latest release page](https://github.com/ksons/gltf-blender-importer/releases/latest) (e.g. [io_scene_gltf-0.3.0.zip](https://github.com/ksons/gltf-blender-importer/releases/download/v0.3.0/io_scene_gltf-0.3.0.zip)). You can install it via the "**Install Add-on from File...**" button on the "**Add-ons**" page. Don't forget to also activate the addon by clicking its checkbox in the addons list.

**Comment by Aie-Aie** [comment]
hi there! may I know where can I have a sample of pick and place operation program in bge?
