### ISSUE TITLE
The addon doesn't shouw up in the list of add-ons after intallation

### ISSUE THREAD

**Issue by alehro** [ksons/gltf-blender-importer#6]
When I try to install it using "Install addon from file" button in user preferences and pointing directly to the __init__.py it doesn't appear in addon's list.
When I renamed the file to glTF2Importer.py and the installed all appeared fine. So, I suggest to rename the file.

Blender version 2.79, Windows 10

**Comment by iwanPlays** [comment]
I tried "install addon from file" both with the zip (failed) and after extraction with the .py (since can't select folders) and both failed.

The solution I found was move the folder containing the .py into addons

![image](https://user-images.githubusercontent.com/25465450/33123677-14847e46-cf7b-11e7-9d6d-e8613cb8e3ef.png)

**Comment by ksons** [comment]
You can now install the addon from the io_scene_gltf-x.y.z.zip file linked from the README and from the [lastest release](io_scene_gltf-0.3.0.zip).
